[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "engine/node.lua"
pattern = "function Node:update(dt) end"
position = "after"
payload = '''

--Determine touch behaviour
function Node:simple_touch()
    return true
end

function Node:can_long_press() return nil end
function Node:can_hover_on_drag() return true end

'''
match_indent = false
